function init(self)
	msg.post("#camera", "acquire_camera_focus") -- <1>
	--go.set_position(vmath.vector3(-568, -320, 0)) -- <4>
end

function on_message(self, message_id, message, sender)
	if message_id == hash("follow") then -- <2>
		go.set_parent(".", sender) -- <3>
		go.set_position(vmath.vector3(-568, -320, 0)) -- <4>
	elseif message_id == hash("unfollow") then -- <5>
		go.set_parent("camera", nil, true)
	end
end